"""Add entry_time and exit_time columns

Revision ID: a60dd6d26f2c
Revises: 
Create Date: 2025-01-24 23:19:36.554187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60dd6d26f2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('exit_time', sa.String(length=50), nullable=True))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('exit_time')
        batch_op.drop_column('entry_time')

    # ### end Alembic commands ###
